version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/search_intelligence_development
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - PROMETHEUS_EXPORTER_HOST=prometheus
      - PROMETHEUS_EXPORTER_PORT=9394
    depends_on:
      - mongodb
      - redis
      - minio
      - prometheus
    volumes:
      - .:/app
    command: bundle exec rails server -b 0.0.0.0

  worker:
    build: .
    environment:
      - RAILS_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/search_intelligence_development
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - PROMETHEUS_EXPORTER_HOST=prometheus
      - PROMETHEUS_EXPORTER_PORT=9394
    depends_on:
      - mongodb
      - redis
      - minio
      - prometheus
    volumes:
      - .:/app
    command: bundle exec sidekiq

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=search_intelligence_development
    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api

volumes:
  redis_data:
  mongodb_data:
  minio_data:
  prometheus_data:
